#!/usr/bin/env sh
#YABAI STUFF
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calculator$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Messenger" manage=off
yabai -m rule --add app="^Authy Desktop" manage=off
yabai -m rule --add app="^Pritunl" manage=off
yabai -m rule --add app="^Messages" manage=off
yabai -m rule --add app="^Slack$" title="Window Title" border=off

yabai -m config window_border_blur off

yabai -m config mouse_follows_focus        off            \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             on             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.1            \
                window_animation_duration  0.1            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                auto_balance               off            \
                auto_padding               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                window_border              on             \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                layout                     bsp            \
                top_padding                0              \
                bottom_padding             2              \
                left_padding               2              \
                right_padding              2              \
                window_gap                 10

echo "yabai configuration loaded.."
